# Generated by Django 5.1.2 on 2024-11-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_admin_doctors_labreport_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabReport',
            new_name='HealthLabreport',
        ),
    ]
