# Generated by Django 5.1.3 on 2024-11-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_admin_last_login_admin_profile_image_admin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_image',
            field=models.ImageField(blank=True, default='doctor1.png', null=True, upload_to='admin_profiles/'),
        ),
    ]
