# Generated by Django 5.1.3 on 2024-11-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_clinicadmin_healthprofessional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('CLINIC_ADMIN', 'Clinic Administrator'), ('HEALTH_PROFESSIONAL', 'Healthcare Professional')], max_length=25),
        ),
    ]
